export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>ProyectoSaludRemota</title>
  <base href="https://danielonofre1234.github.io/Proyecto-de-Salud-en-Telemedicina-TODO-18/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<style>*{margin:0;padding:0;box-sizing:border-box}html,body{width:100%;height:100%;overflow-x:hidden;font-family:Arial,Helvetica,sans-serif}button{cursor:pointer}input,button{max-width:100%}
</style><link rel="stylesheet" href="styles-HOTYT4JM.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-HOTYT4JM.css"></noscript><style ng-app-id="ng">.patients-page[_ngcontent-ng-c3856529387]{padding:20px}.title[_ngcontent-ng-c3856529387]{font-size:28px;margin-bottom:10px}.back-btn[_ngcontent-ng-c3856529387]{margin-bottom:15px;background:#555;color:#fff;border:none;padding:8px 14px;border-radius:6px;cursor:pointer}.form-card[_ngcontent-ng-c3856529387], .profile-card[_ngcontent-ng-c3856529387]{background:#fff;padding:25px;border-radius:12px;box-shadow:0 5px 15px #0000001a;max-width:500px}input[_ngcontent-ng-c3856529387]{display:block;width:100%;margin:10px 0;padding:8px;border-radius:6px;border:1px solid #ccc}button[_ngcontent-ng-c3856529387]{margin-top:10px}.field[_ngcontent-ng-c3856529387]{display:flex;justify-content:space-between;align-items:center;margin:15px 0}.field[_ngcontent-ng-c3856529387]   label[_ngcontent-ng-c3856529387]{font-weight:700}.field[_ngcontent-ng-c3856529387]   span[_ngcontent-ng-c3856529387]{display:flex;align-items:center;gap:10px}.field[_ngcontent-ng-c3856529387]   button[_ngcontent-ng-c3856529387]{background:#007bff;color:#fff;border:none;padding:5px 10px;border-radius:6px;cursor:pointer}.sessions[_ngcontent-ng-c3856529387]{margin-top:20px;font-size:16px}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click","input","compositionstart","compositionend"],["blur"]);</script>
  <app-root ng-version="21.2.4" ngh="1" ng-server-context="ssg"><router-outlet></router-outlet><app-patients _nghost-ng-c3856529387 ngh="0"><div _ngcontent-ng-c3856529387 class="patients-page"><h1 _ngcontent-ng-c3856529387 class="title">Perfil del Paciente</h1><button _ngcontent-ng-c3856529387 class="back-btn" jsaction="click:;">⬅ Volver</button><div _ngcontent-ng-c3856529387 class="form-card"><h2 _ngcontent-ng-c3856529387>Registrar paciente</h2><input _ngcontent-ng-c3856529387 type="text" placeholder="Nombre" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><input _ngcontent-ng-c3856529387 type="number" placeholder="Edad" value="0" class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><input _ngcontent-ng-c3856529387 type="text" placeholder="Teléfono" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><input _ngcontent-ng-c3856529387 type="email" placeholder="Correo" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><button _ngcontent-ng-c3856529387 jsaction="click:;">Guardar datos</button></div><!----><!----></div></app-patients><!----></app-root>
<link rel="modulepreload" href="chunk-LV4Z7622.js"><script src="main-SIMMB5DD.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{"t":{"5":"t16","6":"t17"},"c":{"5":[{"i":"t16","r":1}],"6":[]}},{"c":{"0":[{"i":"c3856529387","r":1}]}}]}</script></body></html>`;